#!/bin/sh
set -eu

# Setup the environment
TEMP=$(mktemp -d)
mv dist $TEMP/

cleanup() {
    mv $TEMP/dist dist
}

trap cleanup EXIT HUP INT TERM

# Run the tests
export LXD_TEST_DRACONIAN_PROXY=1
(cd test/ && script --flush --return -c "./main.sh" test.log)
